#include "user_functions.h"
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

typedef struct { const char *p; char *err; size_t n; } FP;
static void err(FP *p,const char *s){if(p->err&&p->n)snprintf(p->err,p->n,"%s",s);}
static void ws(FP*p){while(isspace((unsigned char)*p->p))p->p++;}
static bool word(FP*p,const char*w){size_t n;ws(p);n=strlen(w);if(strncmp(p->p,w,n)|| (isalnum((unsigned char)p->p[n])||p->p[n]=='_'))return false;p->p+=n;return true;}
static char *id(FP*p){const char*s;size_t n;char*r;ws(p);if(!isalpha((unsigned char)*p->p)&&*p->p!='_')return NULL;s=p->p++;while(isalnum((unsigned char)*p->p)||*p->p=='_')p->p++;n=(size_t)(p->p-s);r=malloc(n+1);if(r){memcpy(r,s,n);r[n]=0;}return r;}
static MilenaFunctionNode *node(MilenaFunctionNodeType t){MilenaFunctionNode*n=calloc(1,sizeof*n);if(n)n->type=t;return n;}
static bool add(MilenaFunctionNode*n,MilenaFunctionNode*c){MilenaFunctionNode**v=realloc(n->children,(n->child_count+1)*sizeof*c);if(!v)return false;n->children=v;n->children[n->child_count++]=c;return true;}
static MilenaFunctionNode *expr(FP*p,MilenaFunction*fn);
static MilenaFunctionNode *primary(FP*p,MilenaFunction*fn){double d;char *s;MilenaFunctionNode*n;size_t i;ws(p);if(*p->p=='('){p->p++;n=expr(p,fn);ws(p);if(*p->p!=')'){err(p,"Se esperaba )");return NULL;}p->p++;return n;}if(isdigit((unsigned char)*p->p)||*p->p=='.'){char*x;d=strtod(p->p,&x);p->p=x;n=node(MILENA_FN_NUMBER);if(n)n->number=d;return n;}s=id(p);if(!s){err(p,"Se esperaba expresión numérica");return NULL;}ws(p);if(*p->p=='('){p->p++;n=node(MILENA_FN_CALL);n->name=s;ws(p);if(*p->p!=')')for(;;){MilenaFunctionNode*a=expr(p,fn);if(!a||!add(n,a)){err(p,"Memoria insuficiente");return NULL;}ws(p);if(*p->p==')')break;if(*p->p!=','){err(p,"Se esperaba ,");return NULL;}p->p++;}p->p++;return n;}for(i=0;i<fn->parameter_count;i++)if(!strcmp(s,fn->parameters[i].name)){free(s);n=node(MILENA_FN_PARAMETER);n->index=i;return n;}for(i=0;i<fn->local_count;i++)if(!strcmp(s,fn->local_names[i])){free(s);n=node(MILENA_FN_LOCAL);n->index=i;return n;}free(s);err(p,"Variable no declarada");return NULL;}
static MilenaFunctionNode *expr(FP*p,MilenaFunction*fn){MilenaFunctionNode*l=primary(p,fn);if(!l)return NULL;for(;;){char op;MilenaFunctionNode*r,*n;ws(p);op=*p->p;if(op!='+'&&op!='-'&&op!='*'&&op!='/')break;p->p++;r=primary(p,fn);if(!r)return NULL;n=node(op=='+'?MILENA_FN_ADD:op=='-'?MILENA_FN_SUB:op=='*'?MILENA_FN_MUL:MILENA_FN_DIV);if(!add(n,l)||!add(n,r))return NULL;l=n;}return l;}
static bool parse_one(FP*p,MilenaFunctionTable*t){MilenaFunction*f=calloc(1,sizeof*f);char*s;MilenaFunctionNode*seq,*ret;size_t i; if(!word(p,"funcion")){free(f);return false;}f->name=id(p);if(!f->name){err(p,"Se esperaba nombre de función");free(f);return false;}ws(p);if(*p->p!='('){err(p,"Se esperaba (");return false;}p->p++;ws(p);if(*p->p!=')')for(;;){s=id(p);if(!s){err(p,"Se esperaba parámetro");return false;}f->parameters=realloc(f->parameters,(f->parameter_count+1)*sizeof*f->parameters);f->parameters[f->parameter_count++].name=s;ws(p);if(*p->p==')')break;if(*p->p!=','){err(p,"Se esperaba ,");return false;}p->p++;}p->p++;ws(p);if(*p->p!='{'){err(p,"Se esperaba {");return false;}p->p++;seq=node(MILENA_FN_SEQUENCE);while(1){ws(p);if(*p->p=='}')break;if(word(p,"variable")){s=id(p);if(!s){err(p,"Se esperaba variable");return false;}f->local_names=realloc(f->local_names,(f->local_count+1)*sizeof*f->local_names);f->local_names[f->local_count++]=s;ws(p);if(*p->p++!='='){err(p,"Se esperaba =");return false;}MilenaFunctionNode*x=expr(p,f);if(!x)return false;MilenaFunctionNode*d=node(MILENA_FN_LOCAL_DECL);d->index=f->local_count-1;add(d,x);add(seq,d);ws(p);if(*p->p++!=';'){err(p,"Se esperaba ;");return false;}}else if(word(p,"retorna")){ret=node(MILENA_FN_RETURN);add(ret,expr(p,f));add(seq,ret);ws(p);if(*p->p++!=';'){err(p,"Se esperaba ;");return false;} }else {err(p,"Solo se admiten variable y retorna");return false;}}p->p++;f->body=seq;if(!milena_function_table_add(t,f)){err(p,"Función duplicada");return false;}return true;}
bool milena_parse_numeric_functions(const char*source,MilenaFunctionTable*t,char*e,size_t n){FP p={source,e,n};if(!source||!t){err(&p,"Argumento inválido");return false;}while(1){ws(&p);if(!*p.p)break;if(!parse_one(&p,t))return false;}return true;}
